"""German theological and liturgical vocabulary for Layer 2 language detection."""

from __future__ import annotations


COVERAGE_STATUS = "v1_floor"

ARCHAIC_FORMS: dict[str, str] = {}

# Layer 2 vocabulary — German theological/liturgical/biblical terms.
# Sources: Luther Bible, Lutheran and Reformed German liturgical tradition,
# German Pietist literature. Distinctive German forms preferred for exclusive-
# match disambiguation against Latin/English/French in short blocks.
VOCAB: frozenset[str] = frozenset({
    # R55 fixture tokens
    "Gnade", "unseres", "Herrn", "Jesus", "Christus", "Gott", "ist", "die",
    "Liebe", "und", "wer", "in", "der", "bleibt", "Gebet", "Bibellesen",
    "sind", "Grundlage", "des", "christlichen", "Lebens", "Kirche", "Gottes",
    "Fundament", "Wahrheit", "Heilige", "Geist", "wird", "euch", "alle",
    "leiten", "Haupt", "seinen", "Leibes", "Reformation", "hat", "Evangelium",
    "neu", "entdeckt", "Luther", "übersetzte", "Bibel", "ins", "Deutsche",
    "Glaube", "Hoffnung", "diese", "drei", "Wort", "Ewigkeit",
    "Christus", "Haupt",
    # Core German theological vocabulary
    "Herr", "Heiland", "Erlöser", "Vater", "Sohn", "Heiliger", "Geist",
    "Frieden", "Erlösung", "Heil", "Gemeinde", "Bibel", "Taufe", "Abendmahl",
    "Buße", "Sünde", "Vergebung", "Gericht", "Auferstehung", "Himmel",
    "Engel", "Propheten", "Apostel", "Jünger", "Schöpfer", "Reich", "Predigt",
    "Heiligung", "Rechtfertigung", "Versöhnung", "Opfer", "Blut", "Kreuz",
    "Bund", "Verheißung", "Gesetz", "Psalmen", "Psalm", "Gottesdienst",
    "Lehre", "Bekenntnis", "Glaubensbekenntnis", "Katechismus", "Augsburgisches",
    "Konkordie", "Schmalkaldische", "Artikel", "Konfession",
    # German names of biblical figures
    "Abraham", "Isaak", "Jakob", "Mose", "Aaron", "Mirjam", "Josua", "Kaleb",
    "Gideon", "Simson", "Rut", "Naomi", "Samuel", "Saul", "David", "Salomo",
    "Elia", "Elisa", "Jesaja", "Jeremia", "Hesekiel", "Daniel", "Hosea",
    "Joel", "Amos", "Obadja", "Jona", "Micha", "Nahum", "Habakuk",
    "Zephanja", "Haggai", "Sacharja", "Maleachi", "Esra", "Nehemia",
    "Ester", "Hiob", "Petrus", "Paulus", "Johannes", "Maria", "Josef",
    "Matthäus", "Markus", "Lukas", "Andreas", "Jakobus", "Philippus",
    "Bartholomäus", "Thomas", "Judas", "Stefanus", "Barnabas", "Silas",
    "Timotheus", "Titus", "Philemon",
    # Names of German theologians
    "Melanchthon", "Bugenhagen", "Zwingli", "Bullinger", "Bucer",
    "Müntzer", "Karlstadt", "Spalatin", "Cranach", "Tetzel",
    "Wittenberg", "Eisleben", "Erfurt", "Worms", "Augsburg", "Heidelberg",
    "Tübingen", "Halle", "Berlin", "München", "Köln", "Hamburg", "Bremen",
    "Frankfurt", "Stuttgart", "Dresden", "Leipzig", "Nürnberg",
    "Deutschland", "Österreich", "Schweiz", "deutsch", "deutsche",
    "deutscher", "deutsches", "deutschen",
    # Common German function words (distinct from Latin/English/French)
    "das", "den", "dem", "ein", "eine", "einer", "einen", "einem", "eines",
    "es", "sich", "auf", "als", "auch", "bei", "durch", "nach", "aus",
    "über", "an", "am", "im", "zum", "zur", "nicht", "mit", "für", "von",
    "zu", "er", "sie", "wir", "ihr", "uns", "man", "wie", "was", "wo",
    "wenn", "dass", "daß", "aber", "oder", "doch", "noch", "schon", "mehr",
    "sehr", "nur", "bis", "seit", "vor", "gegen", "um", "ob", "ja", "nein",
    "ihn", "ihm", "ihnen", "ihrer", "ihres", "ihrem", "ihren", "dessen",
    "deren", "denen", "welche", "welcher", "welches", "welchen", "welchem",
    # German verb forms - sein, haben, werden
    "bin", "bist", "ist", "sind", "seid", "war", "warst", "waren", "wart",
    "gewesen", "sei", "seien", "wäre", "wären", "habe", "hast", "hat",
    "haben", "habt", "hatte", "hattest", "hatten", "hattet", "gehabt",
    "hätte", "hätten", "werde", "wirst", "wird", "werden", "werdet",
    "wurde", "wurdest", "wurden", "wurdet", "geworden", "würde", "würden",
    # Common German verbs
    "kommen", "komme", "kommst", "kommt", "kommen", "kam", "kamen",
    "gekommen", "gehen", "gehe", "gehst", "geht", "gehen", "ging", "gingen",
    "gegangen", "sehen", "sehe", "siehst", "sieht", "sehen", "sah", "sahen",
    "gesehen", "machen", "mache", "machst", "macht", "machen", "machte",
    "machten", "gemacht", "sagen", "sage", "sagst", "sagt", "sagen",
    "sagte", "sagten", "gesagt", "geben", "gebe", "gibst", "gibt", "geben",
    "gab", "gaben", "gegeben", "nehmen", "nehme", "nimmst", "nimmt",
    "nehmen", "nahm", "nahmen", "genommen", "halten", "halte", "hältst",
    "hält", "halten", "hielt", "hielten", "gehalten", "lassen", "lasse",
    "läßt", "lässt", "lassen", "ließ", "ließen", "gelassen", "stehen",
    "stehe", "stehst", "steht", "stehen", "stand", "standen", "gestanden",
    "liegen", "liege", "liegst", "liegt", "liegen", "lag", "lagen",
    "gelegen", "sitzen", "sitze", "sitzt", "sitzen", "saß", "saßen",
    "gesessen", "denken", "denke", "denkst", "denkt", "denken", "dachte",
    "dachten", "gedacht", "wissen", "weiß", "weißt", "wißt", "wissen",
    "wußte", "wußten", "wusste", "wussten", "gewußt", "gewusst",
    "können", "kann", "kannst", "könnt", "können", "konnte", "konnten",
    "gekonnt", "müssen", "muß", "muss", "mußt", "musst", "müßt", "müsst",
    "müssen", "mußte", "musste", "mußten", "mussten", "gemußt", "gemusst",
    "dürfen", "darf", "darfst", "dürft", "dürfen", "durfte", "durften",
    "gedurft", "wollen", "will", "willst", "wollt", "wollen", "wollte",
    "wollten", "gewollt", "sollen", "soll", "sollst", "sollt", "sollen",
    "sollte", "sollten", "gesollt", "mögen", "mag", "magst", "mögt",
    "mögen", "mochte", "mochten", "gemocht",
    # German nouns - religious
    "Christentum", "Religion", "Glaube", "Glauben", "Glaubens", "Glaubende",
    "Gläubige", "Gläubigen", "Christen", "Christ", "Christin", "Lehre",
    "Lehrer", "Lehrerin", "Schüler", "Schülerin", "Lernen", "Lernens",
    "Wissen", "Wissenschaft", "Theologie", "Philosophie", "Geschichte",
    "Tradition", "Brauch", "Sitte", "Gewohnheit",
    "Pfarrer", "Pastor", "Priester", "Bischof", "Erzbischof", "Papst",
    "Kardinal", "Diakon", "Diakonisse", "Mönch", "Nonne", "Abt", "Äbtissin",
    "Vikar", "Kaplan", "Prediger", "Predigerin", "Missionar", "Missionarin",
    "Mission", "Missionen", "Bekehrung", "Bekehrungen", "Buße", "Beichte",
    "Sakrament", "Sakramente", "Liturgie", "Messe", "Andacht", "Andachten",
    # Common everyday words
    "Mann", "Männer", "Frau", "Frauen", "Kind", "Kinder", "Junge", "Jungen",
    "Mädchen", "Familie", "Familien", "Bruder", "Brüder", "Schwester",
    "Schwestern", "Eltern", "Vater", "Väter", "Mutter", "Mütter", "Sohn",
    "Söhne", "Tochter", "Töchter", "Großvater", "Großmutter", "Enkel",
    "Enkelin", "Onkel", "Tante", "Neffe", "Nichte", "Cousin", "Cousine",
    "Freund", "Freunde", "Freundin", "Freundinnen", "Feind", "Feinde",
    "Nachbar", "Nachbarn", "Nachbarin", "Volk", "Völker", "Nation",
    "Nationen", "Land", "Länder", "Stadt", "Städte", "Dorf", "Dörfer",
    "Haus", "Häuser", "Wohnung", "Wohnungen", "Tür", "Türen", "Fenster",
    "Zimmer", "Küche", "Wohnzimmer", "Schlafzimmer", "Bad", "Garten",
    "Gärten", "Straße", "Straßen", "Weg", "Wege", "Platz", "Plätze",
    "Markt", "Märkte", "Geschäft", "Geschäfte", "Schule", "Schulen",
    "Universität", "Universitäten", "Krankenhaus", "Krankenhäuser",
    # Nature
    "Sonne", "Mond", "Stern", "Sterne", "Himmel", "Erde", "Welt", "Meer",
    "Meere", "See", "Seen", "Fluß", "Fluss", "Flüsse", "Bach", "Bäche",
    "Berg", "Berge", "Tal", "Täler", "Hügel", "Wald", "Wälder", "Wiese",
    "Wiesen", "Feld", "Felder", "Baum", "Bäume", "Blume", "Blumen",
    "Blatt", "Blätter", "Wurzel", "Wurzeln", "Frucht", "Früchte",
    "Wasser", "Feuer", "Luft", "Wind", "Winde", "Regen", "Schnee", "Eis",
    "Sturm", "Stürme", "Wolke", "Wolken", "Tau", "Nebel",
    # Time
    "Tag", "Tage", "Nacht", "Nächte", "Morgen", "Mittag", "Abend",
    "Mitternacht", "Stunde", "Stunden", "Minute", "Minuten", "Sekunde",
    "Sekunden", "Woche", "Wochen", "Monat", "Monate", "Jahr", "Jahre",
    "Jahrhundert", "Jahrhunderte", "Jahrtausend", "Jahrtausende",
    "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Sonnabend",
    "Samstag", "Sonntag", "Januar", "Februar", "März", "April", "Mai",
    "Juni", "Juli", "August", "September", "Oktober", "November",
    "Dezember", "Frühling", "Sommer", "Herbst", "Winter", "Jahreszeit",
    "Jahreszeiten", "heute", "gestern", "morgen", "jetzt", "damals",
    "früher", "später", "bald", "gleich", "sofort", "nie", "niemals",
    "immer", "manchmal", "oft", "selten",
    # Adjectives
    "gut", "gute", "guter", "gutes", "guten", "gutem",
    "schlecht", "schlechte", "schlechter", "schlechtes", "schlechten",
    "groß", "große", "großer", "großes", "großen", "großem",
    "klein", "kleine", "kleiner", "kleines", "kleinen", "kleinem",
    "neu", "neue", "neuer", "neues", "neuen", "neuem",
    "alt", "alte", "alter", "altes", "alten", "altem",
    "jung", "junge", "junger", "junges", "jungen", "jungem",
    "schön", "schöne", "schöner", "schönes", "schönen", "schönem",
    "häßlich", "hässlich", "lang", "lange", "langer", "langes", "langen",
    "kurz", "kurze", "kurzer", "kurzes", "kurzen", "kurzem",
    "hoch", "hohe", "hoher", "hohes", "hohen", "hohem", "niedrig",
    "niedrige", "niedriger", "stark", "starke", "starker", "starkes",
    "starken", "schwach", "schwache", "schwacher", "schwaches", "schwachen",
    "warm", "warme", "warmer", "warmes", "warmen", "kalt", "kalte",
    "kalter", "kaltes", "kalten", "heiß", "heiße", "heißer",
    "tief", "tiefe", "tiefer", "tiefes", "tiefen",
    "voll", "volle", "voller", "volles", "vollen",
    "leer", "leere", "leerer", "leeres", "leeren",
    "schwer", "schwere", "schwerer", "schweres", "schweren",
    "leicht", "leichte", "leichter", "leichtes", "leichten",
    # Numerals
    "eins", "zwei", "drei", "vier", "fünf", "sechs", "sieben", "acht",
    "neun", "zehn", "elf", "zwölf", "dreizehn", "vierzehn", "fünfzehn",
    "sechzehn", "siebzehn", "achtzehn", "neunzehn", "zwanzig", "dreißig",
    "vierzig", "fünfzig", "sechzig", "siebzig", "achtzig", "neunzig",
    "hundert", "tausend", "Million", "Millionen", "Milliarde", "Milliarden",
    "erst", "zweit", "dritt", "viert", "fünft", "sechst", "siebt", "acht",
    "neunt", "zehnt", "letzte", "letzter", "letztes", "letzten",
    # Adverbs and conjunctions
    "wieder", "auch", "noch", "schon", "bereits", "eben", "gerade",
    "vielleicht", "wahrscheinlich", "sicherlich", "natürlich", "selbstverständlich",
    "vielleicht", "ungefähr", "etwa", "fast", "beinahe", "kaum",
    "ganz", "gar", "völlig", "vollkommen", "absolut", "relativ",
    "ziemlich", "recht", "wirklich", "tatsächlich", "eigentlich",
    "übrigens", "jedenfalls", "wenigstens", "mindestens", "höchstens",
    "deshalb", "deswegen", "daher", "darum", "folglich", "infolgedessen",
    "trotzdem", "dennoch", "nichtsdestoweniger", "andererseits",
    "einerseits", "übrigens", "außerdem", "zudem", "zugleich", "gleichzeitig",
    "während", "indem", "obwohl", "obgleich", "wenngleich", "obschon",
    "damit", "sodaß", "sodass", "falls", "sofern", "soweit", "solange",
    "sobald", "nachdem", "bevor", "ehe", "seit", "seitdem",
    # Theological extras
    "Allmächtige", "allmächtig", "allmächtige", "Schöpfer", "Schöpfung",
    "Schöpfungen", "Geschöpf", "Geschöpfe", "geschaffen", "schaffen",
    "Wahrheit", "Wahrheiten", "wahr", "wahre", "wahrer", "wahres", "wahren",
    "falsch", "falsche", "falscher", "falsches", "falschen",
    "Ewigkeit", "ewig", "ewige", "ewiger", "ewiges", "ewigen", "ewigem",
    "zeitlich", "zeitliche", "zeitlicher", "zeitliches", "zeitlichen",
    "unsterblich", "unsterbliche", "sterblich", "sterbliche",
    "Seele", "Seelen", "Geist", "Geister", "geistlich", "geistliche",
    "leiblich", "leibliche", "irdisch", "irdische", "himmlisch", "himmlische",
    "göttlich", "göttliche", "göttlicher", "göttliches", "göttlichen",
    "menschlich", "menschliche", "menschlicher", "menschliches", "menschlichen",
    "Menschheit", "Gottheit", "Gottheiten",
    # Bible-specific German vocabulary
    "Genesis", "Exodus", "Levitikus", "Numeri", "Deuteronomium",
    "Schöpfungsgeschichte", "Sündenfall", "Sintflut", "Babylon", "Babylonisch",
    "Exil", "Diaspora", "Zion", "Jerusalem", "Tempel", "Tempels",
    "Synagoge", "Synagogen", "Kirche", "Kirchen", "Kapelle", "Kapellen",
    "Dom", "Münster", "Basilika", "Basiliken", "Kloster", "Klöster",
    "Altar", "Altäre", "Kanzel", "Kanzeln", "Orgel", "Orgeln",
    "Glocke", "Glocken", "Kreuz", "Kreuze", "Krone", "Kronen",
    # Filler
    "Amen", "Halleluja", "Hosianna", "Selah", "Maranatha",
    # Common German short tokens
    "diesem", "diesen", "dieses", "dieser", "diese", "dies", "jenem",
    "jenen", "jenes", "jener", "jene", "jenes", "jeder", "jede", "jedes",
    "jeden", "jedem", "jedwede", "manche", "mancher", "manches", "manchen",
    "manchem", "viele", "vieler", "vieles", "vielen", "vielem", "wenige",
    "weniger", "weniges", "wenigen", "wenigem", "alle", "aller", "alles",
    "allen", "allem", "keine", "keiner", "keines", "keinen", "keinem",
    "einige", "einiger", "einiges", "einigen", "einigem", "etliche",
    "sämtliche", "sämtlicher", "sämtliches", "sämtlichen", "sämtlichem",
    # Modal particles and intensifiers
    "doch", "ja", "halt", "eben", "schon", "wohl", "denn", "etwa", "vielleicht",
    "bloß", "mal", "ruhig", "eigentlich", "übrigens", "freilich",
    # Religious additions
    "Bekenntnisschriften", "Heilsgeschichte", "Heilswerk", "Heilsplan",
    "Heilszeichen", "Heilstat", "Heilszusage", "Heilszeit", "Heilstag",
    "Heilssucher", "Heilsbote", "Heilsverkündigung", "Heilsweg",
    "Sündenbock", "Sündenfall", "Sündflut", "Sündenpfuhl", "Sündenvergebung",
    "Gnadenstuhl", "Gnadenmittel", "Gnadenwahl", "Gnadengabe", "Gnadenzeit",
    "Gottesfurcht", "Gottesliebe", "Gotteslob", "Gotteswort", "Gottesdienst",
    "Glaubensartikel", "Glaubenslehre", "Glaubensbekenntnis", "Glaubenssatz",
    "Christustag", "Christkind", "Christbaum", "Christmette", "Christfest",
})
