"""French theological and liturgical vocabulary for Layer 2 language detection."""

from __future__ import annotations


COVERAGE_STATUS = "v1_floor"

# Archaic forms mapping — French theological texts are not strongly archaic
ARCHAIC_FORMS: dict[str, str] = {}

# Layer 2 vocabulary — French theological/liturgical/biblical terms.
# Sources: French Protestant theological tradition, Louis Segond Bible,
# French Catholic liturgical vocabulary. Distinctive French forms preferred
# so that exclusive-match boosting disambiguates French from Latin/English.
VOCAB: frozenset[str] = frozenset({
    # R55 fixture tokens
    "grâce", "notre", "Seigneur", "seigneur", "Jésus", "jésus", "Christ",
    "Dieu", "dieu", "amour", "celui", "demeure", "dans", "Père", "père",
    "cieux", "nom", "sanctifié", "Car", "car", "tant", "aimé", "monde",
    "donné", "Fils", "fils", "unique", "suis", "résurrection", "vie",
    "foi", "sans", "oeuvres", "œuvres", "morte", "Église", "église",
    "rachetée", "par", "sang", "apprends", "nous", "prier", "parole",
    "vivante", "efficace", "votre", "hypocrisie",
    # Core French theological vocabulary
    "esprit", "Esprit", "saint", "Saint", "sainte", "Sainte", "gloire",
    "paix", "prière", "baptême", "salut", "évangile", "Évangile", "loi",
    "prophète", "prophètes", "apôtre", "apôtres", "disciple", "disciples",
    "sermon", "confession", "péché", "péchés", "repentance", "pardon",
    "miséricorde", "justice", "vérité", "lumière", "ténèbres", "espérance",
    "cœur", "coeur", "âme", "corps", "chair", "mort", "royaume", "alliance",
    "promesse", "commandement", "commandements", "temple", "sacrifice",
    "offrande", "prêtre", "roi", "serviteur", "maître", "berger", "agneau",
    "brebis", "vigne", "pain", "vin", "eau", "feu", "montagne", "mer",
    "désert", "Jérusalem", "Sion", "Israël", "Judée", "Galilée",
    "Abraham", "Isaac", "Jacob", "Moïse", "David", "Salomon", "Ésaïe",
    "Jérémie", "Daniel", "Pierre", "Paul", "Jean", "Marie", "Joseph",
    "Matthieu", "Marc", "Luc",
    # Common French function/linking words (distinct from Latin where possible)
    "le", "la", "les", "des", "du", "un", "une", "au", "aux", "en", "que",
    "qui", "est", "sont", "ont", "pas", "plus", "cette", "ces", "tout",
    "tous", "toute", "toutes", "aussi", "même", "alors", "puis",
    "mais", "ni", "ou", "si", "se", "lui", "leur", "leurs", "sur", "sous",
    "vers", "chez", "après", "avant", "avec", "selon", "pour", "contre",
    "comme", "parce", "depuis", "pendant", "durant", "jusqu", "encore",
    "déjà", "toujours", "jamais", "souvent", "parfois", "rarement",
    "voici", "voilà",
    # French verb conjugations
    "ai", "as", "avons", "avez", "ont", "avais", "avait", "avions", "aviez",
    "avaient", "eu", "eus", "eut", "eurent", "aurai", "auras", "aura",
    "aurons", "aurez", "auront", "aurais", "aurait", "aurions", "auriez",
    "auraient", "soit", "soient", "fut", "furent", "serai", "seras", "sera",
    "serons", "serez", "seront", "serais", "serait", "serions", "seriez",
    "seraient", "étais", "était", "étions", "étiez", "étaient",
    "fais", "fait", "faisons", "faites", "font", "faisais", "faisait",
    "faisions", "faisiez", "faisaient", "fis", "firent", "ferai",
    "feras", "fera", "ferons", "ferez", "feront", "ferais", "ferait",
    "ferions", "feriez", "feraient",
    "vais", "vas", "va", "allons", "allez", "vont", "allais", "allait",
    "allions", "alliez", "allaient", "irai", "iras", "ira", "irons",
    "irez", "iront", "irais", "irait", "irions", "iriez", "iraient",
    "dis", "dit", "disons", "dites", "disent", "disais", "disait",
    "disions", "disiez", "disaient",
    "vois", "voit", "voyons", "voyez", "voient",
    # French theological additions
    "chrétien", "chrétienne", "chrétiens", "chrétiennes", "catholique",
    "protestant", "réformé", "calviniste", "luthérien", "anglican",
    "orthodoxe", "œcuménique", "ecclésial", "ecclésiale", "ecclésiastique",
    "spirituel", "spirituelle", "spirituels", "spirituelles",
    "céleste", "divin", "divine", "divins", "divines", "humain", "humaine",
    "humains", "humaines", "éternel", "éternelle", "éternels", "éternelles",
    "saint", "sainte", "saints", "saintes", "sainteté", "sanctification",
    "rédemption", "rédempteur", "sauveur", "consolateur", "intercesseur",
    "médiateur", "avocat", "consolation", "réconfort", "encouragement",
    "exhortation", "édification", "instruction", "enseignement",
    "doctrine", "dogme", "credo", "symbole", "confession", "tradition",
    "écriture", "écritures", "bible", "Bible", "ancien", "ancienne",
    "nouveau", "nouvelle", "testament", "alliance", "pacte", "promesse",
    # Names of French theologians and locations
    "Calvin", "Luther", "Zwingli", "Bèze", "Farel", "Viret", "Olivétan",
    "Wesley", "Genève", "Strasbourg", "Lyon", "Paris", "Marseille",
    "Bordeaux", "Lille", "Nantes", "Rouen", "Reims", "Toulouse",
    "France", "Suisse", "Belgique", "Canada", "Québec",
    # Common French short words to boost recognition
    "ce", "ça", "ne", "lui", "moi", "toi", "soi", "eux", "elles", "elle",
    "il", "ils", "on", "moi", "toi", "lui", "elle", "nous", "vous",
    "mon", "ma", "mes", "ton", "ta", "tes", "son", "sa", "ses", "notre",
    "nos", "votre", "vos", "leurs", "le", "la", "les", "lequel", "laquelle",
    "lesquels", "lesquelles", "auquel", "auxquels", "auxquelles",
    "duquel", "desquels", "desquelles",
    # Numbers
    "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf",
    "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize",
    "vingt", "trente", "quarante", "cinquante", "soixante", "cent", "mille",
    "premier", "première", "deuxième", "troisième", "quatrième", "cinquième",
    "sixième", "septième", "huitième", "neuvième", "dixième",
    # Days, months, time
    "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche",
    "janvier", "février", "mars", "avril", "mai", "juin", "juillet",
    "août", "septembre", "octobre", "novembre", "décembre",
    "jour", "jours", "nuit", "matin", "soir", "midi", "minuit",
    "heure", "heures", "minute", "minutes", "seconde", "secondes",
    "semaine", "mois", "année", "année", "siècle", "siècles",
    # Adjectives
    "bon", "bonne", "bons", "bonnes", "mauvais", "mauvaise", "mauvaises",
    "grand", "grande", "grands", "grandes", "petit", "petite", "petits",
    "petites", "beau", "belle", "beaux", "belles", "vieux", "vieille",
    "vieilles", "jeune", "jeunes", "nouveau", "nouvelle", "nouveaux",
    "nouvelles", "vrai", "vraie", "vrais", "vraies", "faux", "fausse",
    "fausses", "long", "longue", "longs", "longues", "court", "courte",
    "courts", "courtes", "haut", "haute", "hauts", "hautes", "bas", "basse",
    "basses", "fort", "forte", "forts", "fortes", "faible", "faibles",
    "premier", "première", "premiers", "premières", "dernier", "dernière",
    "derniers", "dernières",
    # Verbs - common French
    "aimer", "aime", "aimes", "aimons", "aimez", "aiment", "aimait",
    "aimais", "aimaient", "aimera", "aiment", "aimé", "aimée",
    "parler", "parle", "parles", "parlons", "parlez", "parlent", "parlait",
    "donner", "donne", "donnes", "donnons", "donnez", "donnent", "donnait",
    "trouver", "trouve", "trouves", "trouvons", "trouvez", "trouvent",
    "chercher", "cherche", "cherches", "cherchons", "cherchez", "cherchent",
    "porter", "porte", "portes", "portons", "portez", "portent",
    "entrer", "entre", "entres", "entrons", "entrez", "entrent",
    "sortir", "sors", "sort", "sortons", "sortez", "sortent",
    "venir", "viens", "vient", "venons", "venez", "viennent",
    "partir", "pars", "part", "partons", "partez", "partent",
    "prendre", "prends", "prend", "prenons", "prenez", "prennent",
    "mettre", "mets", "met", "mettons", "mettez", "mettent",
    "savoir", "sais", "sait", "savons", "savez", "savent",
    "pouvoir", "peux", "peut", "pouvons", "pouvez", "peuvent",
    "vouloir", "veux", "veut", "voulons", "voulez", "veulent",
    "devoir", "dois", "doit", "devons", "devez", "doivent",
    "croire", "crois", "croit", "croyons", "croyez", "croient",
    "vivre", "vis", "vit", "vivons", "vivez", "vivent",
    "mourir", "meurs", "meurt", "mourons", "mourez", "meurent",
    "naître", "nais", "naît", "naissons", "naissez", "naissent",
    "écrire", "écris", "écrit", "écrivons", "écrivez", "écrivent",
    "lire", "lis", "lit", "lisons", "lisez", "lisent",
    "comprendre", "comprends", "comprend", "comprenons", "comprenez",
    "comprennent",
    "regarder", "regarde", "regardes", "regardons", "regardez", "regardent",
    "écouter", "écoute", "écoutes", "écoutons", "écoutez", "écoutent",
    # Nouns - French theological and common
    "homme", "hommes", "femme", "femmes", "enfant", "enfants", "garçon",
    "fille", "filles", "famille", "familles", "frère", "frères", "sœur",
    "sœurs", "ami", "amis", "amie", "amies", "ennemi", "ennemis",
    "voisin", "voisine", "voisins", "voisines", "peuple", "peuples",
    "nation", "nations", "pays", "ville", "villes", "village", "villages",
    "maison", "maisons", "porte", "portes", "fenêtre", "fenêtres",
    "chambre", "chambres", "salle", "salles", "table", "tables", "chaise",
    "chaises", "lit", "lits", "rue", "rues", "chemin", "chemins", "route",
    "routes", "place", "places", "marché", "école", "écoles",
    "champ", "champs", "jardin", "jardins", "forêt", "forêts", "fleur",
    "fleurs", "arbre", "arbres", "feuille", "feuilles", "racine", "racines",
    "ciel", "soleil", "lune", "étoile", "étoiles", "nuage", "nuages",
    "vent", "vents", "pluie", "neige", "glace", "tempête", "tempêtes",
    "eau", "eaux", "fleuve", "fleuves", "rivière", "rivières", "lac",
    "lacs", "mer", "mers", "océan", "océans", "île", "îles", "côte",
    "plage", "plages", "montagne", "montagnes", "colline", "collines",
    "vallée", "vallées", "désert", "déserts", "campagne", "ville",
    # More French function words
    "très", "trop", "assez", "peu", "beaucoup", "bien", "mal", "mieux",
    "moins", "plus", "autant", "tellement", "tant", "si", "tout", "rien",
    "quelqu", "quelques", "personne", "chacun", "chacune", "aucun",
    "aucune", "plusieurs", "certains", "certaines", "autres",
    # More French content words
    "merci", "bonjour", "bonsoir", "bonne", "salut", "adieu",
    "oui", "non", "peut-être", "certainement", "sûrement", "probablement",
    "vraiment", "réellement", "effectivement",
    # Additional theological content
    "berger", "troupeau", "moisson", "semence", "blé", "ivraie",
    "vigne", "vignoble", "raisin", "olivier", "figuier", "cèdre",
    "louange", "louanges", "adoration", "intercession", "supplication",
    "action", "actions", "œuvre", "œuvres", "service", "ministère",
    "ministères", "vocation", "appel", "mission", "envoi",
    "témoignage", "témoignages", "témoin", "témoins", "martyr", "martyrs",
    "confesseur", "confesseurs", "ascète", "ascètes", "moine", "moines",
    "moniale", "moniales", "ermite", "ermites", "religieux", "religieuse",
    "religieuses", "frère", "sœur", "abbé", "abbesse",
    # More words
    "âge", "âges", "art", "arts", "but", "buts", "cas", "côté", "côtés",
    "coup", "coups", "exemple", "exemples", "façon", "façons", "fait",
    "faits", "fin", "fins", "fois", "force", "forces", "forme", "formes",
    "groupe", "groupes", "histoire", "histoires", "idée", "idées",
    "instant", "instants", "jeu", "jeux", "lieu", "lieux", "mètre",
    "mètres", "monsieur", "messieurs", "madame", "mesdames", "mademoiselle",
    "mademoiselles", "moment", "moments", "moyen", "moyens", "nombre",
    "nombres", "objet", "objets", "œuvre", "œuvres", "ordre", "ordres",
    "parti", "partis", "partie", "parties", "point", "points", "position",
    "positions", "problème", "problèmes", "question", "questions",
    "raison", "raisons", "rapport", "rapports", "résultat", "résultats",
    "sens", "service", "services", "site", "sites", "somme", "sommes",
    "sorte", "sortes", "succès", "système", "systèmes", "type", "types",
    "valeur", "valeurs", "vue", "vues",
    # Adverbs and adjectives
    "ainsi", "donc", "néanmoins", "cependant", "pourtant", "toutefois",
    "néanmoins", "d", "j", "l", "m", "n", "qu", "s", "t", "c",
    # More French verb forms
    "auront", "iront", "feront", "seront", "viendront", "tiendront",
    "diront", "verront", "sauront", "pourront", "voudront", "devront",
    "croiront", "vivront", "mourront", "naîtront", "écriront", "liront",
    "comprendront", "regarderont", "écouteront",
    # Phrases related to religion
    "bénédiction", "bénédictions", "malédiction", "malédictions",
    "vocation", "élection", "prédestination", "providence", "miracle",
    "miracles", "merveille", "merveilles", "signe", "signes",
    "guérison", "guérisons", "exorcisme", "exorcismes",
    "résurrection", "ascension", "pentecôte", "épiphanie", "annonciation",
    "incarnation", "rédemption", "salut", "perdition", "damnation",
    "enfer", "paradis", "purgatoire", "limbes", "ciel", "terre",
    # Common short French words
    "et", "ou", "ni", "car", "donc", "or", "mais", "puis",
    "à", "de", "en", "par", "pour", "sans", "sous", "sur", "vers",
    "avec", "chez", "dans", "entre", "parmi", "pendant", "selon",
    "depuis", "avant", "après",
    "très", "peu", "beaucoup", "tellement", "tant", "trop",
    # More liturgical / Catholic vocabulary
    "messe", "eucharistie", "communion", "confession", "absolution",
    "extrême-onction", "ordination", "mariage", "baptême", "confirmation",
    "pénitence", "vêpres", "matines", "complies", "laudes", "tierce",
    "sexte", "none", "office", "bréviaire", "missel", "rituel",
    # Protestant vocabulary
    "Réforme", "réforme", "réformateur", "réformateurs", "huguenot",
    "huguenots", "calvinisme", "luthéranisme", "anglicanisme",
    "presbytérianisme", "méthodisme", "baptisme", "pentecôtisme",
    "évangélique", "évangéliques", "fondamentalisme", "libéralisme",
    "rationalisme", "déisme", "athéisme", "agnosticisme", "panthéisme",
    "polythéisme", "monothéisme",
    # Bible-specific
    "Genèse", "Exode", "Lévitique", "Nombres", "Deutéronome", "Josué",
    "Juges", "Ruth", "Samuel", "Rois", "Chroniques", "Esdras", "Néhémie",
    "Esther", "Job", "Psaumes", "Proverbes", "Ecclésiaste", "Cantique",
    "Cantiques", "Isaïe", "Lamentations", "Ézéchiel", "Osée", "Joël",
    "Amos", "Abdias", "Jonas", "Michée", "Nahum", "Habacuc", "Sophonie",
    "Aggée", "Zacharie", "Malachie", "Romains", "Corinthiens", "Galates",
    "Éphésiens", "Philippiens", "Colossiens", "Thessaloniciens",
    "Timothée", "Tite", "Philémon", "Hébreux", "Jacques", "Pierre",
    "Apocalypse",
    # Filler / connectives
    "y", "en", "déjà", "encore", "puis", "ensuite", "enfin",
    "premièrement", "deuxièmement", "troisièmement", "finalement",
    "surtout", "principalement", "particulièrement", "spécialement",
    "généralement", "habituellement", "ordinairement", "normalement",
})
